# Project information
site_name: Kudo
site_url: https://kudo.divisioncero.com/
site_author: Peter Vargas
site_description: >-
  Cybersecurity Compliance | Open Source | Template | Cloud Security Alliance

# Repository
repo_name: PetterVargas/kudo-divisioncero-com
repo_url: https://github.com/PetterVargas/kudo-divisioncero-com
edit_uri: edit/main/docs/
icon:
  repo: fontawesome/brands/github

# Copyright
copyright: Copyright &copy; 2025 DivisiónCero

nav:
  - Overview: index.md
  - Policies:
    - Policies: policies/index.md
    - Information Security Policy: policies/information-security-policy.md
    - Statement of Applicability (SoA): policies/statement-of-applicability-SoA.md
    - Information Security Governance: policies/information-security-governance.md
    - Information Security Framework Policy: policies/information-security-framework-policy.md
    - Information Security Committee: policies/information-security-committee.md
    - Management Commitment: policies/management-commitment.md
    - Information Security Risk Matrix: policies/information-security-risk-matrix.md
    - Control Measurement Evaluation Plan: policies/control-measurement-evaluation-plan.md
    - Security Governance Role Model: policies/security-governance-role-model.md
    - Internal Security Audit Policy: policies/internal-security-audit-policy.md
    - Technical Audit Procedure: policies/technical-audit-procedure.md
    - Annual Audit Plan: policies/annual-audit-plan.md
    - Corrective Actions Register Plan: policies/corrective-actions-register-plan.md
    - Secure Development Policy: policies/secure-development-policy.md
    - Secure Coding Standard: policies/secure-coding-standard.md
    - Code Review Security Testing: policies/code-review-security-testing.md
    - Secure API Integration Guidelines: policies/secure-api-integration-guidelines.md
    - Business Continuity Policy: policies/business-continuity-policy.md
    - Operational Continuity Plan: policies/operational-continuity-plan.md
    - Disaster Recovery Plan: policies/disaster-recovery-plan.md
    - BCP & DRP Testing Strategy: policies/bcp-drp-testing-strategy.md
    - Change Management Policy: policies/change-management-policy.md
    - Version Control Process: policies/version-control-process.md
    - Critical Production Change Log: policies/critical-production-change-log.md
    - Data Encryption Policy: policies/data-encryption-policy.md
    - Cryptographic Key Inventory: policies/cryptographic-key-inventory.md
    - Digital Certificate Management: policies/digital-certificate-management.md
    - Third Party Assessment Policy: policies/third-party-assessment-policy.md
    - Critical Supplier Due Diligence: policies/critical-supplier-due-diligence.md
    - Security Clauses in Contracts: policies/security-clauses-in-contracts.md
    - Datacenter Physical Security Policy: policies/datacenter-physical-security-policy.md
    - Physical Access Control: policies/physical-access-control.md
    - Visitor Log Access: policies/visitor-log-access.md
    - Electrical Continuity Plan: policies/electrical-continuity-plan.md
    - Contingency Disasters: policies/contingency-disasters.md
    - Compliance Certifications: policies/compliance-certifications.md
    - Personal Data Protection Policy: policies/personal-data-protection-policy.md
    - Information Classification: policies/information-classification.md
    - Retention and Disposal Policy: policies/retention-and-disposal-policy.md
    - Encryption Mechanisms: policies/encryption-mechanisms.md
    - Corporate Cybersecurity Governance: policies/corporate-cybersecurity-governance.md
    - Cybersecurity Risk Matrix: policies/cybersecurity-risk-matrix.md
    - Risk Treatment Plan: policies/risk-treatment-plan.md
    - Regulatory Compliance Policy: policies/regulatory-compliance-policy.md
    - Employee Lifecycle Security Policy: policies/employee-lifecycle-security-policy.md
    - NDA: policies/nda.md
    - Security Awareness Training: policies/security-awareness-training.md
    - Secure Offboarding Process: policies/secure-offboarding-process.md
    - Access Control Policy: policies/access-control-policy.md
    - User Provisioning Procedure: policies/user-provisioning-procedure.md
    - Privileged Access Management: policies/privileged-access-management.md
    - Access Authentication Logs: policies/access-authentication-logs.md
    - Cloud Interoperability Policy: policies/cloud-interoperability-policy.md
    - Migration Portability Strategy: policies/migration-portability-strategy.md
    - Virtual Environment Security Policy: policies/virtual-environment-security-policy.md
    - Patch Hardening Management: policies/patch-hardening-management.md
    - Container Security Control: policies/container-security-control.md
    - Security Event Monitoring Policy: policies/security-event-monitoring-policy.md
    - SIEM Event Correlation: policies/siem-event-correlation.md
    - Incident Response Plan: policies/incident-response-plan.md
    - Log Registration Retention: policies/log-registration-retention.md
    - Incident Management Policy: policies/incident-management-policy.md
    - Digital Forensic Investigation: policies/digital-forensic-investigation.md
    - Incident Log Lessons Learned: policies/incident-log-lessons-learned.md
    - Vulnerability Management Policy: policies/vulnerability-management-policy.md
    - Continuous Vulnerability Scanning: policies/continuous-vulnerability-scanning.md
    - Remediation Plan Exceptions: policies/remediation-plan-exceptions.md
    - Endpoint Management Policy: policies/endpoint-management-policy.md
    - BYOD Device Control: policies/byod-device-control.md
    - Endpoint Patching Configuration: policies/endpoint-patching-configuration.md
  - Baseline: 
    - Baseline: baseline/index.md
    - A&A: baseline/A&A/index.md
    - AIS: baseline/AIS/index.md
    - BCR: baseline/BCR/index.md
    - CCC: baseline/CCC/index.md  
    - CEK: baseline/CEK/index.md
    - DCS: baseline/DCS/index.md
    - DSP: baseline/DSP/index.md
    - GRC: baseline/GRC/index.md
    - HRS: baseline/HRS/index.md
    - IAM: baseline/IAM/index.md
    - IPY: baseline/IPY/index.md
    - IVS: baseline/IVS/index.md
    - LOG: baseline/LOG/index.md
    - SEF: baseline/SEF/index.md
    - STA: baseline/STA/index.md
    - TVM: baseline/TVM/index.md
    - UEM: baseline/UEM/index.md
    

# Customization
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/divisioncero-logo.png
  favicon: assets/favicon.ico
  language: en

  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to system preference
  
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - announce.dismiss
    - navigation.footer
    - content.action
    - content.tabs.link
    - content.tooltips
    - navigation.path
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.prune
    - content.action.edit
    - content.action.view
  
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.critic

extra_css:
  - overrides/stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

extra_javascript:
  - overrides/javascripts/iconsearch_index.js
  - overrides/javascripts/extra.js
  - overrides/javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  alternate:
    - name: Español
      link: /es/
      lang: es
  
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/PetterVargas/divisioncero.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/divisioncero
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/divisioncero/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/petervargas/
    - icon: fontawesome/brands/discord
      link: https://www.discord.com/divisioncero/

  homepage: https://kudo.divisioncero.com

  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  
  analytics:
    provider: google
    property: GTM-TCV984S 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

  version:
    provider: mike
    default: latest
